"""Add characters and association tables

Revision ID: 1a2b3c4d5e6f
Revises: 02b35f707b57
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = '02b35f707b57' # Assuming this is the latest auto-generated one
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('appearance_description', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('video_clip_urls', sa.JSON(), nullable=True),
    sa.Column('notes_for_llm', sa.Text(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True, server_default='10'),
    sa.Column('dexterity', sa.Integer(), nullable=True, server_default='10'),
    sa.Column('constitution', sa.Integer(), nullable=True, server_default='10'),
    sa.Column('intelligence', sa.Integer(), nullable=True, server_default='10'),
    sa.Column('wisdom', sa.Integer(), nullable=True, server_default='10'),
    sa.Column('charisma', sa.Integer(), nullable=True, server_default='10'),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False) # Index on name as it might be queried often

    op.create_table('character_campaign_association',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_campaign_association')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
