"""add export_format_preference to character table

Revision ID: 2b5c879d0a3e
Revises: 02b35f707b57
Create Date: YYYY-MM-DD HH:MM:SS.ssssss # Will be auto-filled by Alembic usually

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5c879d0a3e'
down_revision = '02b35f707b57' # Assuming this is the latest prior migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('export_format_preference', sa.String(), nullable=True, server_default='complex'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'export_format_preference')
    # ### end Alembic commands ###
