"""add_thematic_image_fields_to_campaigns

Revision ID: 88aee1ef707a
Revises: 98424bc8b1bb
Create Date: <Ensure your actual create date is here from the filename>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88aee1ef707a' # YOUR ACTUAL REVISION ID
down_revision: Union[str, None] = '98424bc8b1bb' # YOUR ACTUAL DOWN_REVISION ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('thematic_image_url', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('thematic_image_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'thematic_image_prompt')
    op.drop_column('campaigns', 'thematic_image_url')
    # ### end Alembic commands ###