"""add_context_and_types_to_features

Revision ID: f0aecf752cf0
Revises: 7f41b03c9035
Create Date: 2025-07-02 16:36:14.396278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0aecf752cf0'
down_revision: Union[str, None] = '7f41b03c9035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('required_context', sa.JSON(), nullable=True))
    op.add_column('features', sa.Column('compatible_types', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'compatible_types')
    op.drop_column('features', 'required_context')
    # ### end Alembic commands ###