"""Add memory_summary to chat_messages table

Revision ID: <your_new_revision_id_here_004>
Revises: <id_of_previous_migration_script_here_003>
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'manual_004_add_memory_summary_to_chat_messages'  # Replace with actual ID generated by `alembic revision`
down_revision = 'manual_003_reformat_chat_messages_json'  # Replace with ID of 'manual_003_reformat_chat_messages_json.py' or your actual previous head
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('memory_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'memory_summary')
    # ### end Alembic commands ###
